spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: gym-service
            uri: lb://gym-service
            predicates:
              - Path=/gym/**
            filters:
              - StripPrefix=1

          - id: training-service
            uri: lb://training-service
            predicates:
              - Path=/training/**
            filters:
              - StripPrefix=1

          - id: authentication-server
            uri: lb://authentication-server
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 8085
