jwt:
  secret:
    123487321678683219089080989532412321321433242324353445
spring:
  application:
    name: gym-service
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 12345678


  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: false
      trusted: com.epam.hibernate
    pool:
      block-if-full: true
      block-if-full-timeout: -1
      enabled: false
      idle-timeout: 30000
      max-connections: 10
      time-between-expiration-check: -1
      use-anonymous-producers: true

  jms:
    listener:
      auto-startup: true
      max-concurrency: 10
      session:
        acknowledge-mode: auto
      min-concurrency: 5
    pub-sub-domain: false
    template:
      default-destination:
      delivery-mode: non_persistent
      priority: 100
      qos-enabled: true
      receive-timeout: 1000
      time-to-live: 36000


server:
  port: 8081
  error:
    include-message: always
management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    enabled-by-default: false
  info:
    env:
      enabled: true
  endpoint:
    prometheus:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
      group:
        check:
          include:
            - DB
            - externalService
    mappings:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
info:
  app:
    name: @project.name@
    description: dev profile
    version: @project.version@
    java:
      version: @java.version@
  build-timestamp: @maven.build.timestamp@
---
spring:
  config:
    activate:
      on-profile: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_admin
info:
  app:
    name: @project.name@
    description: admin profile
    version: @project.version@
    java:
      version: @java.version@
  build-timestamp: @maven.build.timestamp@
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    java:
      version: @java.version@
  build-timestamp: @maven.build.timestamp@

---
spring:
  profiles:
    active: admin