jwt:
  secret:
    123487321678683219089080989532412321321433242324353445
spring:
  application:
    name: authentication-server
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 12345678
server:
  port: 8084
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate
---
spring:
  config:
    activate:
      on-profile: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_admin
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
---
spring:
  profiles:
    active: admin